/* Generated By:JJTree: Do not edit this line. ASTbitwiseAndExpression.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javascriptInterpreter.tree;

import javascriptInterpreter.parser.*;

public
class ASTbitwiseAndExpression extends SimpleNode {
  public ASTbitwiseAndExpression(int id) {
    super(id);
  }

  public ASTbitwiseAndExpression(Javascript p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavascriptVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=db473fe44eb2fe2f328d8c1113d47c75 (do not edit this line) */
