/* Generated By:JavaCC: Do not edit this line. JavascriptTreeConstants.java Version 7.0.5 */
package javascriptInterpreter.tree;

import javascriptInterpreter.parser.*;

public interface JavascriptTreeConstants
{
  public int JJTPRIMARYEXPRESSION = 0;
  public int JJTLITERAL = 1;
  public int JJTARRAYLITERAL = 2;
  public int JJTVOID = 3;
  public int JJTSPREADELEMENT = 4;
  public int JJTOBJECTLITERAL = 5;
  public int JJTPROPERTYDEFINITION = 6;
  public int JJTPARENTHESIZEDEXPRESSION = 7;
  public int JJTLEFTSIDEEXPRESSION = 8;
  public int JJTCALLEXPRESSION = 9;
  public int JJTARGUMENTS = 10;
  public int JJTNEWEXPRESSION = 11;
  public int JJTMEMBEREXPRESSION = 12;
  public int JJTUPDATEEXPRESSION = 13;
  public int JJTUNARYEXPRESSION = 14;
  public int JJTEXPONENTIATIONOPERATOR = 15;
  public int JJTMULTIPLICATIVEEXPRESSION = 16;
  public int JJTADDITIVEEXPRESSION = 17;
  public int JJTSHIFTEXPRESSION = 18;
  public int JJTRELATIONALEXPRESSION = 19;
  public int JJTEQUALITYEXPRESSION = 20;
  public int JJTBITWISEANDEXPRESSION = 21;
  public int JJTBITWISEXOREXPRESSION = 22;
  public int JJTBITWISEOREXPRESSION = 23;
  public int JJTLOGICALANDEXPRESSION = 24;
  public int JJTLOGICALOREXPRESSION = 25;
  public int JJTCONDITIONALEXPRESSION = 26;
  public int JJTASSIGNMENTEXPRESSION = 27;
  public int JJTEXPRESSION = 28;
  public int JJTFUNCTIONEXPRESSION = 29;
  public int JJTSTATEMENT = 30;
  public int JJTEMPTYSTATEMENT = 31;
  public int JJTEXPRESSIONSTATEMENT = 32;
  public int JJTVARIABLEDEFINITION = 33;
  public int JJTVARIABLEDECLARATIONLIST = 34;
  public int JJTVARIABLEDECLARATION = 35;
  public int JJTBLOCK = 36;
  public int JJTLABELEDSTATEMENT = 37;
  public int JJTIFSTATEMENT = 38;
  public int JJTSWITCHSTATEMENT = 39;
  public int JJTCASEBLOCK = 40;
  public int JJTCASECLAUSES = 41;
  public int JJTCASECLAUSE = 42;
  public int JJTDEFAULTCLAUSE = 43;
  public int JJTDOSTATEMENT = 44;
  public int JJTWHILESTATEMENT = 45;
  public int JJTFORSTATEMENT = 46;
  public int JJTFORHEADER = 47;
  public int JJTFORINITIALIZER = 48;
  public int JJTFORINHEADER = 49;
  public int JJTFORINBINDING = 50;
  public int JJTCONTINUESTATEMENT = 51;
  public int JJTBREAKSTATEMENT = 52;
  public int JJTRETURNSTATEMENT = 53;
  public int JJTTHROWSTATEMENT = 54;
  public int JJTTRYSTATEMENT = 55;
  public int JJTCATCHCLAUSES = 56;
  public int JJTCATCHCLAUSE = 57;
  public int JJTFINALLYCLAUSE = 58;
  public int JJTNAMEDFUNCTION = 59;
  public int JJTANONYMOUSFUNCTION = 60;
  public int JJTFORMALPARAMETERS = 61;
  public int JJTFUNCTIONBODY = 62;
  public int JJTTOPSTATEMENT = 63;
  public int JJTTOPSTATEMENTS = 64;
  public int JJTPROGRAM = 65;


  public String[] jjtNodeName = {
    "primaryExpression",
    "literal",
    "arrayLiteral",
    "void",
    "spreadElement",
    "objectLiteral",
    "propertyDefinition",
    "parenthesizedExpression",
    "leftSideExpression",
    "callExpression",
    "arguments",
    "newExpression",
    "memberExpression",
    "updateExpression",
    "unaryExpression",
    "exponentiationOperator",
    "multiplicativeExpression",
    "additiveExpression",
    "shiftExpression",
    "relationalExpression",
    "equalityExpression",
    "bitwiseAndExpression",
    "bitwiseXorExpression",
    "bitwiseOrExpression",
    "logicalAndExpression",
    "logicalOrExpression",
    "conditionalExpression",
    "assignmentExpression",
    "expression",
    "functionExpression",
    "statement",
    "emptyStatement",
    "expressionStatement",
    "variableDefinition",
    "variableDeclarationList",
    "variableDeclaration",
    "block",
    "labeledStatement",
    "ifStatement",
    "switchStatement",
    "caseBlock",
    "caseClauses",
    "caseClause",
    "defaultClause",
    "doStatement",
    "whileStatement",
    "forStatement",
    "forHeader",
    "forInitializer",
    "forInHeader",
    "forInBinding",
    "continueStatement",
    "breakStatement",
    "returnStatement",
    "throwStatement",
    "tryStatement",
    "catchClauses",
    "catchClause",
    "finallyClause",
    "namedFunction",
    "anonymousFunction",
    "formalParameters",
    "functionBody",
    "topStatement",
    "topStatements",
    "program",
  };
}
/* JavaCC - OriginalChecksum=b6ce9ad98a33760c60f87da7782bd462 (do not edit this line) */
