/* Javascript.java */
/* Generated By:JavaCC: Do not edit this line. Javascript.java */
import java.io.*;
public class Javascript implements JavascriptConstants {

        public static void main(String args[]) throws ParseException{
                        try{
                InputStream in = new FileInputStream("correct.js");
                Javascript parser = new Javascript(in);
                parser.program();
                System.out.println("Successfully parsed the grammar");
                        }catch(IOException e){
                e.printStackTrace();
                    }
        }

        public static boolean isNotEndOfArray() {
        int i = 1;
        while(getToken(i).image == ","){
            i++;
        }
        return getToken(i).image != "]";
    }

  static final public void primaryExpression() throws ParseException {
    trace_call("primaryExpression");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case THIS:{
        jj_consume_token(THIS);
        break;
        }
      case IDENTIFIER_NAME:{
        jj_consume_token(IDENTIFIER_NAME);
        break;
        }
      case NULL_LITERAL:
      case BOOLEAN_LITERAL:
      case STRING_LITERAL:
      case NUMERIC_LITERAL:{
        literal();
        break;
        }
      case 55:{
        arrayLiteral();
        break;
        }
      case 59:{
        objectLiteral();
        break;
        }
      case FUNCTION:{
        functionExpression();
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("primaryExpression");
    }
}

  static final public void literal() throws ParseException {
    trace_call("literal");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case NULL_LITERAL:{
        jj_consume_token(NULL_LITERAL);
        break;
        }
      case BOOLEAN_LITERAL:{
        jj_consume_token(BOOLEAN_LITERAL);
        break;
        }
      case NUMERIC_LITERAL:{
        jj_consume_token(NUMERIC_LITERAL);
        break;
        }
      case STRING_LITERAL:{
        jj_consume_token(STRING_LITERAL);
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("literal");
    }
}

  static final public void arrayLiteral() throws ParseException {
    trace_call("arrayLiteral");
    try {

      jj_consume_token(55);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 57:{
        ellision();
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FUNCTION:
      case THIS:
      case NULL_LITERAL:
      case BOOLEAN_LITERAL:
      case STRING_LITERAL:
      case NUMERIC_LITERAL:
      case IDENTIFIER_NAME:
      case 55:
      case 58:
      case 59:{
        elementList();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 57:{
          ellision();
          break;
          }
        default:
          jj_la1[3] = jj_gen;
          ;
        }
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        ;
      }
      jj_consume_token(56);
    } finally {
      trace_return("arrayLiteral");
    }
}

  static final public void ellision() throws ParseException {
    trace_call("ellision");
    try {

      label_1:
      while (true) {
        jj_consume_token(57);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 57:{
          ;
          break;
          }
        default:
          jj_la1[5] = jj_gen;
          break label_1;
        }
      }
    } finally {
      trace_return("ellision");
    }
}

  static final public void elementList() throws ParseException {
    trace_call("elementList");
    try {

      arrayElement();
      label_2:
      while (true) {
        if (isNotEndOfArray()) {
          ;
        } else {
          break label_2;
        }
        ellision();
        arrayElement();
      }
    } finally {
      trace_return("elementList");
    }
}

  static final public void arrayElement() throws ParseException {
    trace_call("arrayElement");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FUNCTION:
      case THIS:
      case NULL_LITERAL:
      case BOOLEAN_LITERAL:
      case STRING_LITERAL:
      case NUMERIC_LITERAL:
      case IDENTIFIER_NAME:
      case 55:
      case 59:{
        assignmentExpression();
        break;
        }
      case 58:{
        spreadElement();
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("arrayElement");
    }
}

  static final public void spreadElement() throws ParseException {
    trace_call("spreadElement");
    try {

      jj_consume_token(58);
      assignmentExpression();
    } finally {
      trace_return("spreadElement");
    }
}

  static final public void objectLiteral() throws ParseException {
    trace_call("objectLiteral");
    try {

      jj_consume_token(59);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER_NAME:{
        propertyDefinitionList();
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        ;
      }
      jj_consume_token(60);
    } finally {
      trace_return("objectLiteral");
    }
}

  static final public void propertyDefinitionList() throws ParseException {
    trace_call("propertyDefinitionList");
    try {

      propertyDefinition();
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 57:{
          ;
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          break label_3;
        }
        jj_consume_token(57);
        propertyDefinition();
      }
    } finally {
      trace_return("propertyDefinitionList");
    }
}

  static final public void propertyDefinition() throws ParseException {
    trace_call("propertyDefinition");
    try {

      jj_consume_token(IDENTIFIER_NAME);
      jj_consume_token(61);
      assignmentExpression();
    } finally {
      trace_return("propertyDefinition");
    }
}

  static final public void leftSideExpression() throws ParseException {
    trace_call("leftSideExpression");
    try {

      callExpression();
    } finally {
      trace_return("leftSideExpression");
    }
}

  static final public void callExpression() throws ParseException {
    trace_call("callExpression");
    try {

      primaryExpression();
    } finally {
      trace_return("callExpression");
    }
}

  static final public void postFixExpression() throws ParseException {
    trace_call("postFixExpression");
    try {

      leftSideExpression();
    } finally {
      trace_return("postFixExpression");
    }
}

  static final public void unaryExpression() throws ParseException {
    trace_call("unaryExpression");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DELETE:{
        jj_consume_token(DELETE);
        leftSideExpression();
        break;
        }
      case FUNCTION:
      case THIS:
      case TYPEOF:
      case VOID:
      case NULL_LITERAL:
      case BOOLEAN_LITERAL:
      case STRING_LITERAL:
      case NUMERIC_LITERAL:
      case IDENTIFIER_NAME:
      case 55:
      case 59:
      case 62:
      case 63:{
        label_4:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case TYPEOF:
          case VOID:
          case 62:
          case 63:{
            ;
            break;
            }
          default:
            jj_la1[9] = jj_gen;
            break label_4;
          }
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case VOID:{
            jj_consume_token(VOID);
            break;
            }
          case TYPEOF:{
            jj_consume_token(TYPEOF);
            break;
            }
          case 62:{
            jj_consume_token(62);
            break;
            }
          case 63:{
            jj_consume_token(63);
            break;
            }
          default:
            jj_la1[10] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
        postFixExpression();
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("unaryExpression");
    }
}

  static final public void multiplicativeExpression() throws ParseException {
    trace_call("multiplicativeExpression");
    try {

      label_5:
      while (true) {
        if (jj_2_1(2147483647)) {
          ;
        } else {
          break label_5;
        }
        unaryExpression();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 64:{
          jj_consume_token(64);
          break;
          }
        case 65:{
          jj_consume_token(65);
          break;
          }
        case 66:{
          jj_consume_token(66);
          break;
          }
        default:
          jj_la1[12] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      unaryExpression();
    } finally {
      trace_return("multiplicativeExpression");
    }
}

  static final public void additiveExpression() throws ParseException {
    trace_call("additiveExpression");
    try {

      label_6:
      while (true) {
        if (jj_2_2(2147483647)) {
          ;
        } else {
          break label_6;
        }
        multiplicativeExpression();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 67:{
          jj_consume_token(67);
          break;
          }
        case 68:{
          jj_consume_token(68);
          break;
          }
        default:
          jj_la1[13] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      multiplicativeExpression();
    } finally {
      trace_return("additiveExpression");
    }
}

  static final public void shiftExpression() throws ParseException {
    trace_call("shiftExpression");
    try {

      label_7:
      while (true) {
        if (jj_2_3(2147483647)) {
          ;
        } else {
          break label_7;
        }
        additiveExpression();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 69:{
          jj_consume_token(69);
          break;
          }
        case 70:{
          jj_consume_token(70);
          break;
          }
        case 71:{
          jj_consume_token(71);
          break;
          }
        default:
          jj_la1[14] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      additiveExpression();
    } finally {
      trace_return("shiftExpression");
    }
}

  static final public void relationalExpression() throws ParseException {
    trace_call("relationalExpression");
    try {

      label_8:
      while (true) {
        if (jj_2_4(2147483647)) {
          ;
        } else {
          break label_8;
        }
        shiftExpression();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 72:{
          jj_consume_token(72);
          break;
          }
        case 73:{
          jj_consume_token(73);
          break;
          }
        case 74:{
          jj_consume_token(74);
          break;
          }
        case 75:{
          jj_consume_token(75);
          break;
          }
        case INSTANCEOF:{
          jj_consume_token(INSTANCEOF);
          break;
          }
        case IN:{
          jj_consume_token(IN);
          break;
          }
        default:
          jj_la1[15] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      shiftExpression();
    } finally {
      trace_return("relationalExpression");
    }
}

  static final public void equalityExpression() throws ParseException {
    trace_call("equalityExpression");
    try {

      label_9:
      while (true) {
        if (jj_2_5(2147483647)) {
          ;
        } else {
          break label_9;
        }
        relationalExpression();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 76:{
          jj_consume_token(76);
          break;
          }
        case 77:{
          jj_consume_token(77);
          break;
          }
        case 78:{
          jj_consume_token(78);
          break;
          }
        case 79:{
          jj_consume_token(79);
          break;
          }
        default:
          jj_la1[16] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      relationalExpression();
    } finally {
      trace_return("equalityExpression");
    }
}

  static final public void bitwiseAndExpression() throws ParseException {
    trace_call("bitwiseAndExpression");
    try {

      label_10:
      while (true) {
        if (jj_2_6(2147483647)) {
          ;
        } else {
          break label_10;
        }
        equalityExpression();
        jj_consume_token(80);
      }
      equalityExpression();
    } finally {
      trace_return("bitwiseAndExpression");
    }
}

  static final public void bitwiseXorExpression() throws ParseException {
    trace_call("bitwiseXorExpression");
    try {

      label_11:
      while (true) {
        if (jj_2_7(2147483647)) {
          ;
        } else {
          break label_11;
        }
        bitwiseAndExpression();
        jj_consume_token(81);
      }
      bitwiseAndExpression();
    } finally {
      trace_return("bitwiseXorExpression");
    }
}

  static final public void bitwiseOrExpression() throws ParseException {
    trace_call("bitwiseOrExpression");
    try {

      label_12:
      while (true) {
        if (jj_2_8(2147483647)) {
          ;
        } else {
          break label_12;
        }
        bitwiseXorExpression();
        jj_consume_token(82);
      }
      bitwiseXorExpression();
    } finally {
      trace_return("bitwiseOrExpression");
    }
}

  static final public void logicalAndExpression() throws ParseException {
    trace_call("logicalAndExpression");
    try {

      label_13:
      while (true) {
        if (jj_2_9(2147483647)) {
          ;
        } else {
          break label_13;
        }
        bitwiseOrExpression();
        jj_consume_token(83);
      }
      bitwiseOrExpression();
    } finally {
      trace_return("logicalAndExpression");
    }
}

  static final public void logicalOrExpression() throws ParseException {
    trace_call("logicalOrExpression");
    try {

      label_14:
      while (true) {
        if (jj_2_10(2147483647)) {
          ;
        } else {
          break label_14;
        }
        logicalAndExpression();
        jj_consume_token(84);
      }
      logicalAndExpression();
    } finally {
      trace_return("logicalOrExpression");
    }
}

  static final public void conditionalExpression() throws ParseException {
    trace_call("conditionalExpression");
    try {

      logicalOrExpression();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 85:{
        jj_consume_token(85);
        assignmentExpression();
        jj_consume_token(61);
        assignmentExpression();
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        ;
      }
    } finally {
      trace_return("conditionalExpression");
    }
}

  static final public void assignmentExpression() throws ParseException {
    trace_call("assignmentExpression");
    try {

      leftSideExpression();
    } finally {
      trace_return("assignmentExpression");
    }
}

  static final public void expression() throws ParseException {
    trace_call("expression");
    try {

      assignmentExpression();
      label_15:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 57:{
          ;
          break;
          }
        default:
          jj_la1[18] = jj_gen;
          break label_15;
        }
        jj_consume_token(57);
        assignmentExpression();
      }
    } finally {
      trace_return("expression");
    }
}

  static final public void functionExpression() throws ParseException {
    trace_call("functionExpression");
    try {

      if (jj_2_11(2)) {
        namedFunction();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case FUNCTION:{
          anonymousFunction();
          break;
          }
        default:
          jj_la1[19] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } finally {
      trace_return("functionExpression");
    }
}

  static final public void statement() throws ParseException {
    trace_call("statement");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 86:{
        emptyStatement();
        break;
        }
      case VAR:{
        variableDefinition();
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        if (jj_2_12(2147483647)) {
          block();
        } else if (jj_2_13(2147483647)) {
          labeledStatement();
        } else {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case IF:{
            ifStatement();
            break;
            }
          case SWITCH:{
            switchStatement();
            break;
            }
          case DO:{
            doStatement();
            break;
            }
          case WHILE:{
            whileStatement();
            break;
            }
          case FOR:{
            forStatement();
            break;
            }
          case CONTINUE:{
            continueStatement();
            break;
            }
          case BREAK:{
            breakStatement();
            break;
            }
          case RETURN:{
            returnStatement();
            break;
            }
          case THROW:{
            throwStatement();
            break;
            }
          case TRY:{
            tryStatement();
            break;
            }
          case FUNCTION:
          case THIS:
          case NULL_LITERAL:
          case BOOLEAN_LITERAL:
          case STRING_LITERAL:
          case NUMERIC_LITERAL:
          case IDENTIFIER_NAME:
          case 55:
          case 59:{
            expressionStatement();
            break;
            }
          default:
            jj_la1[21] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
      }
    } finally {
      trace_return("statement");
    }
}

  static final public void emptyStatement() throws ParseException {
    trace_call("emptyStatement");
    try {

      jj_consume_token(86);
    } finally {
      trace_return("emptyStatement");
    }
}

  static final public void expressionStatement() throws ParseException {
    trace_call("expressionStatement");
    try {

      expression();
    } finally {
      trace_return("expressionStatement");
    }
}

  static final public void variableDefinition() throws ParseException {
    trace_call("variableDefinition");
    try {

      jj_consume_token(VAR);
      variableDeclarationList();
    } finally {
      trace_return("variableDefinition");
    }
}

  static final public void variableDeclarationList() throws ParseException {
    trace_call("variableDeclarationList");
    try {

      variableDeclaration();
      label_16:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 57:{
          ;
          break;
          }
        default:
          jj_la1[22] = jj_gen;
          break label_16;
        }
        jj_consume_token(57);
        variableDeclaration();
      }
    } finally {
      trace_return("variableDeclarationList");
    }
}

  static final public void variableDeclaration() throws ParseException {
    trace_call("variableDeclaration");
    try {

      jj_consume_token(IDENTIFIER_NAME);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case 87:{
        jj_consume_token(87);
        assignmentExpression();
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        ;
      }
    } finally {
      trace_return("variableDeclaration");
    }
}

  static final public void block() throws ParseException {
    trace_call("block");
    try {

      jj_consume_token(59);
      label_17:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case BREAK:
        case CONTINUE:
        case DO:
        case FOR:
        case FUNCTION:
        case IF:
        case RETURN:
        case SWITCH:
        case THIS:
        case THROW:
        case TRY:
        case VAR:
        case WHILE:
        case NULL_LITERAL:
        case BOOLEAN_LITERAL:
        case STRING_LITERAL:
        case NUMERIC_LITERAL:
        case IDENTIFIER_NAME:
        case 55:
        case 59:
        case 86:{
          ;
          break;
          }
        default:
          jj_la1[24] = jj_gen;
          break label_17;
        }
        statement();
      }
      jj_consume_token(60);
    } finally {
      trace_return("block");
    }
}

  static final public void labeledStatement() throws ParseException {
    trace_call("labeledStatement");
    try {

      jj_consume_token(IDENTIFIER_NAME);
      jj_consume_token(61);
      if (getToken(1).image != "function") {
        statement();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case FUNCTION:{
          namedFunction();
          break;
          }
        default:
          jj_la1[25] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } finally {
      trace_return("labeledStatement");
    }
}

  static final public void ifStatement() throws ParseException {
    trace_call("ifStatement");
    try {

      jj_consume_token(IF);
      jj_consume_token(88);
      expression();
      jj_consume_token(89);
      statement();
      if (jj_2_14(2)) {
        jj_consume_token(ELSE);
        statement();
      } else {
        ;
      }
    } finally {
      trace_return("ifStatement");
    }
}

  static final public void switchStatement() throws ParseException {
    trace_call("switchStatement");
    try {

      jj_consume_token(SWITCH);
      jj_consume_token(88);
      expression();
      jj_consume_token(89);
      caseBlock();
    } finally {
      trace_return("switchStatement");
    }
}

  static final public void caseBlock() throws ParseException {
    trace_call("caseBlock");
    try {

      jj_consume_token(59);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CASE:{
        caseClauses();
        break;
        }
      default:
        jj_la1[26] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DFLT:{
        defaultClause();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case CASE:{
          caseClauses();
          break;
          }
        default:
          jj_la1[27] = jj_gen;
          ;
        }
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        ;
      }
      jj_consume_token(60);
    } finally {
      trace_return("caseBlock");
    }
}

  static final public void caseClauses() throws ParseException {
    trace_call("caseClauses");
    try {

      label_18:
      while (true) {
        caseClause();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case CASE:{
          ;
          break;
          }
        default:
          jj_la1[29] = jj_gen;
          break label_18;
        }
      }
    } finally {
      trace_return("caseClauses");
    }
}

  static final public void caseClause() throws ParseException {
    trace_call("caseClause");
    try {

      jj_consume_token(CASE);
      expression();
      jj_consume_token(61);
      label_19:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case BREAK:
        case CONTINUE:
        case DO:
        case FOR:
        case FUNCTION:
        case IF:
        case RETURN:
        case SWITCH:
        case THIS:
        case THROW:
        case TRY:
        case VAR:
        case WHILE:
        case NULL_LITERAL:
        case BOOLEAN_LITERAL:
        case STRING_LITERAL:
        case NUMERIC_LITERAL:
        case IDENTIFIER_NAME:
        case 55:
        case 59:
        case 86:{
          ;
          break;
          }
        default:
          jj_la1[30] = jj_gen;
          break label_19;
        }
        statement();
      }
    } finally {
      trace_return("caseClause");
    }
}

  static final public void defaultClause() throws ParseException {
    trace_call("defaultClause");
    try {

      jj_consume_token(DFLT);
      jj_consume_token(61);
      label_20:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case BREAK:
        case CONTINUE:
        case DO:
        case FOR:
        case FUNCTION:
        case IF:
        case RETURN:
        case SWITCH:
        case THIS:
        case THROW:
        case TRY:
        case VAR:
        case WHILE:
        case NULL_LITERAL:
        case BOOLEAN_LITERAL:
        case STRING_LITERAL:
        case NUMERIC_LITERAL:
        case IDENTIFIER_NAME:
        case 55:
        case 59:
        case 86:{
          ;
          break;
          }
        default:
          jj_la1[31] = jj_gen;
          break label_20;
        }
        statement();
      }
    } finally {
      trace_return("defaultClause");
    }
}

  static final public void doStatement() throws ParseException {
    trace_call("doStatement");
    try {

      jj_consume_token(DO);
      statement();
      jj_consume_token(WHILE);
      jj_consume_token(88);
      expression();
      jj_consume_token(89);
    } finally {
      trace_return("doStatement");
    }
}

  static final public void whileStatement() throws ParseException {
    trace_call("whileStatement");
    try {

      jj_consume_token(WHILE);
      jj_consume_token(88);
      expression();
      jj_consume_token(89);
      statement();
    } finally {
      trace_return("whileStatement");
    }
}

  static final public void forStatement() throws ParseException {
    trace_call("forStatement");
    try {

      jj_consume_token(FOR);
      jj_consume_token(88);
      if (jj_2_15(3)) {
        forHeader();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case VAR:{
          forInHeader();
          break;
          }
        default:
          jj_la1[32] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
      jj_consume_token(89);
      statement();
    } finally {
      trace_return("forStatement");
    }
}

  static final public void forHeader() throws ParseException {
    trace_call("forHeader");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FUNCTION:
      case THIS:
      case VAR:
      case NULL_LITERAL:
      case BOOLEAN_LITERAL:
      case STRING_LITERAL:
      case NUMERIC_LITERAL:
      case IDENTIFIER_NAME:
      case 55:
      case 59:{
        forInitializer();
        break;
        }
      default:
        jj_la1[33] = jj_gen;
        ;
      }
      jj_consume_token(86);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FUNCTION:
      case THIS:
      case NULL_LITERAL:
      case BOOLEAN_LITERAL:
      case STRING_LITERAL:
      case NUMERIC_LITERAL:
      case IDENTIFIER_NAME:
      case 55:
      case 59:{
        expression();
        break;
        }
      default:
        jj_la1[34] = jj_gen;
        ;
      }
      jj_consume_token(86);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FUNCTION:
      case THIS:
      case NULL_LITERAL:
      case BOOLEAN_LITERAL:
      case STRING_LITERAL:
      case NUMERIC_LITERAL:
      case IDENTIFIER_NAME:
      case 55:
      case 59:{
        expression();
        break;
        }
      default:
        jj_la1[35] = jj_gen;
        ;
      }
    } finally {
      trace_return("forHeader");
    }
}

  static final public void forInitializer() throws ParseException {
    trace_call("forInitializer");
    try {

      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FUNCTION:
      case THIS:
      case NULL_LITERAL:
      case BOOLEAN_LITERAL:
      case STRING_LITERAL:
      case NUMERIC_LITERAL:
      case IDENTIFIER_NAME:
      case 55:
      case 59:{
        expression();
        break;
        }
      case VAR:{
        jj_consume_token(VAR);
        variableDeclarationList();
        break;
        }
      default:
        jj_la1[36] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
      trace_return("forInitializer");
    }
}

  static final public void forInHeader() throws ParseException {
    trace_call("forInHeader");
    try {

      forInBinding();
      jj_consume_token(IN);
      expression();
    } finally {
      trace_return("forInHeader");
    }
}

  static final public void forInBinding() throws ParseException {
    trace_call("forInBinding");
    try {

      jj_consume_token(VAR);
      variableDeclaration();
    } finally {
      trace_return("forInBinding");
    }
}

  static final public void continueStatement() throws ParseException {
    trace_call("continueStatement");
    try {

      jj_consume_token(CONTINUE);
      if (jj_2_16(2)) {
        jj_consume_token(IDENTIFIER_NAME);
      } else {
        ;
      }
    } finally {
      trace_return("continueStatement");
    }
}

  static final public void breakStatement() throws ParseException {
    trace_call("breakStatement");
    try {

      jj_consume_token(BREAK);
      if (jj_2_17(2)) {
        jj_consume_token(IDENTIFIER_NAME);
      } else {
        ;
      }
    } finally {
      trace_return("breakStatement");
    }
}

  static final public void returnStatement() throws ParseException {
    trace_call("returnStatement");
    try {

      jj_consume_token(RETURN);
      if (jj_2_18(2)) {
        expression();
      } else {
        ;
      }
    } finally {
      trace_return("returnStatement");
    }
}

  static final public void throwStatement() throws ParseException {
    trace_call("throwStatement");
    try {

      jj_consume_token(THROW);
      expression();
    } finally {
      trace_return("throwStatement");
    }
}

  static final public void tryStatement() throws ParseException {
    trace_call("tryStatement");
    try {

      jj_consume_token(TRY);
      block();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CATCH:{
        catchClauses();
        break;
        }
      default:
        jj_la1[37] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FINALLY:{
        finallyClause();
        break;
        }
      default:
        jj_la1[38] = jj_gen;
        ;
      }
    } finally {
      trace_return("tryStatement");
    }
}

  static final public void catchClauses() throws ParseException {
    trace_call("catchClauses");
    try {

      label_21:
      while (true) {
        catchClause();
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case CATCH:{
          ;
          break;
          }
        default:
          jj_la1[39] = jj_gen;
          break label_21;
        }
      }
    } finally {
      trace_return("catchClauses");
    }
}

  static final public void catchClause() throws ParseException {
    trace_call("catchClause");
    try {

      jj_consume_token(CATCH);
      jj_consume_token(88);
      jj_consume_token(IDENTIFIER_NAME);
      jj_consume_token(89);
      block();
    } finally {
      trace_return("catchClause");
    }
}

  static final public void finallyClause() throws ParseException {
    trace_call("finallyClause");
    try {

      jj_consume_token(FINALLY);
      block();
    } finally {
      trace_return("finallyClause");
    }
}

  static final public void namedFunction() throws ParseException {
    trace_call("namedFunction");
    try {

      jj_consume_token(FUNCTION);
      jj_consume_token(IDENTIFIER_NAME);
      jj_consume_token(88);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER_NAME:{
        formalParameters();
        break;
        }
      default:
        jj_la1[40] = jj_gen;
        ;
      }
      jj_consume_token(89);
      jj_consume_token(59);
      if (jj_2_19(1)) {
        functionBody();
      } else {
        ;
      }
      jj_consume_token(60);
    } finally {
      trace_return("namedFunction");
    }
}

  static final public void anonymousFunction() throws ParseException {
    trace_call("anonymousFunction");
    try {

      jj_consume_token(FUNCTION);
      jj_consume_token(88);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER_NAME:{
        formalParameters();
        break;
        }
      default:
        jj_la1[41] = jj_gen;
        ;
      }
      jj_consume_token(89);
      jj_consume_token(59);
      if (jj_2_20(1)) {
        functionBody();
      } else {
        ;
      }
      jj_consume_token(60);
    } finally {
      trace_return("anonymousFunction");
    }
}

  static final public void formalParameters() throws ParseException {
    trace_call("formalParameters");
    try {

      jj_consume_token(IDENTIFIER_NAME);
      label_22:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case 57:{
          ;
          break;
          }
        default:
          jj_la1[42] = jj_gen;
          break label_22;
        }
        jj_consume_token(57);
        jj_consume_token(IDENTIFIER_NAME);
      }
    } finally {
      trace_return("formalParameters");
    }
}

  static final public void functionBody() throws ParseException {
    trace_call("functionBody");
    try {

      topStatements();
    } finally {
      trace_return("functionBody");
    }
}

  static final public void topStatement() throws ParseException {
    trace_call("topStatement");
    try {

      if (getToken(1).image != "function") {
        statement();
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case FUNCTION:{
          namedFunction();
          break;
          }
        default:
          jj_la1[43] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } finally {
      trace_return("topStatement");
    }
}

  static final public void topStatements() throws ParseException {
    trace_call("topStatements");
    try {

      label_23:
      while (true) {
        topStatement();
        if (jj_2_21(1)) {
          ;
        } else {
          break label_23;
        }
      }
    } finally {
      trace_return("topStatements");
    }
}

  static final public void program() throws ParseException {
    trace_call("program");
    try {
Token t = null;
      topStatements();
      jj_consume_token(0);
    } finally {
      trace_return("program");
    }
}

  static private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  static private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  static private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_7()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  static private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_8()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  static private boolean jj_2_9(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_9()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(8, xla); }
  }

  static private boolean jj_2_10(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_10()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(9, xla); }
  }

  static private boolean jj_2_11(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_11()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(10, xla); }
  }

  static private boolean jj_2_12(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_12()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(11, xla); }
  }

  static private boolean jj_2_13(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_13()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(12, xla); }
  }

  static private boolean jj_2_14(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_14()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(13, xla); }
  }

  static private boolean jj_2_15(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_15()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(14, xla); }
  }

  static private boolean jj_2_16(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_16()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(15, xla); }
  }

  static private boolean jj_2_17(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_17()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(16, xla); }
  }

  static private boolean jj_2_18(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_18()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(17, xla); }
  }

  static private boolean jj_2_19(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_19()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(18, xla); }
  }

  static private boolean jj_2_20(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_20()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(19, xla); }
  }

  static private boolean jj_2_21(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_21()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(20, xla); }
  }

  static private boolean jj_3R_106()
 {
    if (jj_scan_token(87)) return true;
    if (jj_3R_68()) return true;
    return false;
  }

  static private boolean jj_3R_101()
 {
    if (jj_scan_token(57)) return true;
    if (jj_3R_100()) return true;
    return false;
  }

  static private boolean jj_3R_79()
 {
    if (jj_scan_token(IF)) return true;
    if (jj_scan_token(88)) return true;
    if (jj_3R_37()) return true;
    if (jj_scan_token(89)) return true;
    if (jj_3R_35()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_14()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_78()
 {
    if (jj_scan_token(IDENTIFIER_NAME)) return true;
    if (jj_scan_token(61)) return true;
    Token xsp;
    xsp = jj_scanpos;
    jj_lookingAhead = true;
    jj_semLA = getToken(1).image != "function";
    jj_lookingAhead = false;
    if (!jj_semLA || jj_3R_128()) {
    jj_scanpos = xsp;
    if (jj_3R_129()) return true;
    }
    return false;
  }

  static private boolean jj_3R_127()
 {
    if (jj_3R_35()) return true;
    return false;
  }

  static private boolean jj_3R_77()
 {
    if (jj_scan_token(59)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_127()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(60)) return true;
    return false;
  }

  static private boolean jj_3R_100()
 {
    if (jj_scan_token(IDENTIFIER_NAME)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_106()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_95()
 {
    if (jj_3R_100()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_101()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_76()
 {
    if (jj_scan_token(VAR)) return true;
    if (jj_3R_95()) return true;
    return false;
  }

  static private boolean jj_3R_89()
 {
    if (jj_3R_37()) return true;
    return false;
  }

  static private boolean jj_3R_64()
 {
    if (jj_3R_89()) return true;
    return false;
  }

  static private boolean jj_3R_63()
 {
    if (jj_3R_88()) return true;
    return false;
  }

  static private boolean jj_3_13()
 {
    if (jj_scan_token(IDENTIFIER_NAME)) return true;
    if (jj_scan_token(61)) return true;
    return false;
  }

  static private boolean jj_3R_110()
 {
    if (jj_3R_115()) return true;
    return false;
  }

  static private boolean jj_3R_62()
 {
    if (jj_3R_87()) return true;
    return false;
  }

  static private boolean jj_3_12()
 {
    if (jj_scan_token(59)) return true;
    return false;
  }

  static private boolean jj_3R_61()
 {
    if (jj_3R_86()) return true;
    return false;
  }

  static private boolean jj_3R_60()
 {
    if (jj_3R_85()) return true;
    return false;
  }

  static private boolean jj_3R_59()
 {
    if (jj_3R_84()) return true;
    return false;
  }

  static private boolean jj_3R_58()
 {
    if (jj_3R_83()) return true;
    return false;
  }

  static private boolean jj_3R_57()
 {
    if (jj_3R_82()) return true;
    return false;
  }

  static private boolean jj_3R_56()
 {
    if (jj_3R_81()) return true;
    return false;
  }

  static private boolean jj_3R_55()
 {
    if (jj_3R_80()) return true;
    return false;
  }

  static private boolean jj_3R_54()
 {
    if (jj_3R_79()) return true;
    return false;
  }

  static private boolean jj_3R_53()
 {
    if (jj_3R_78()) return true;
    return false;
  }

  static private boolean jj_3R_52()
 {
    if (jj_3R_77()) return true;
    return false;
  }

  static private boolean jj_3R_69()
 {
    if (jj_scan_token(57)) return true;
    if (jj_3R_68()) return true;
    return false;
  }

  static private boolean jj_3R_51()
 {
    if (jj_3R_76()) return true;
    return false;
  }

  static private boolean jj_3R_35()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(86)) {
    jj_scanpos = xsp;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) {
    jj_scanpos = xsp;
    if (jj_3R_53()) {
    jj_scanpos = xsp;
    if (jj_3R_54()) {
    jj_scanpos = xsp;
    if (jj_3R_55()) {
    jj_scanpos = xsp;
    if (jj_3R_56()) {
    jj_scanpos = xsp;
    if (jj_3R_57()) {
    jj_scanpos = xsp;
    if (jj_3R_58()) {
    jj_scanpos = xsp;
    if (jj_3R_59()) {
    jj_scanpos = xsp;
    if (jj_3R_60()) {
    jj_scanpos = xsp;
    if (jj_3R_61()) {
    jj_scanpos = xsp;
    if (jj_3R_62()) {
    jj_scanpos = xsp;
    if (jj_3R_63()) {
    jj_scanpos = xsp;
    if (jj_3R_64()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3_11()
 {
    if (jj_3R_34()) return true;
    return false;
  }

  static private boolean jj_3R_105()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_11()) {
    jj_scanpos = xsp;
    if (jj_3R_110()) return true;
    }
    return false;
  }

  static private boolean jj_3R_37()
 {
    if (jj_3R_68()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_69()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_68()
 {
    if (jj_3R_73()) return true;
    return false;
  }

  static private boolean jj_3_10()
 {
    if (jj_3R_33()) return true;
    if (jj_scan_token(84)) return true;
    return false;
  }

  static private boolean jj_3_9()
 {
    if (jj_3R_32()) return true;
    if (jj_scan_token(83)) return true;
    return false;
  }

  static private boolean jj_3_8()
 {
    if (jj_3R_31()) return true;
    if (jj_scan_token(82)) return true;
    return false;
  }

  static private boolean jj_3R_50()
 {
    if (jj_3R_32()) return true;
    if (jj_scan_token(83)) return true;
    return false;
  }

  static private boolean jj_3R_33()
 {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_50()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_32()) return true;
    return false;
  }

  static private boolean jj_3_7()
 {
    if (jj_3R_30()) return true;
    if (jj_scan_token(81)) return true;
    return false;
  }

  static private boolean jj_3R_49()
 {
    if (jj_3R_31()) return true;
    if (jj_scan_token(82)) return true;
    return false;
  }

  static private boolean jj_3R_32()
 {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_49()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_31()) return true;
    return false;
  }

  static private boolean jj_3_6()
 {
    if (jj_3R_29()) return true;
    if (jj_scan_token(80)) return true;
    return false;
  }

  static private boolean jj_3R_48()
 {
    if (jj_3R_30()) return true;
    if (jj_scan_token(81)) return true;
    return false;
  }

  static private boolean jj_3R_31()
 {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_48()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_30()) return true;
    return false;
  }

  static private boolean jj_3_5()
 {
    if (jj_3R_28()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(76)) {
    jj_scanpos = xsp;
    if (jj_scan_token(77)) {
    jj_scanpos = xsp;
    if (jj_scan_token(78)) {
    jj_scanpos = xsp;
    if (jj_scan_token(79)) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_47()
 {
    if (jj_3R_29()) return true;
    if (jj_scan_token(80)) return true;
    return false;
  }

  static private boolean jj_3R_30()
 {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_47()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_29()) return true;
    return false;
  }

  static private boolean jj_3R_74()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(33)) {
    jj_scanpos = xsp;
    if (jj_scan_token(31)) {
    jj_scanpos = xsp;
    if (jj_scan_token(62)) {
    jj_scanpos = xsp;
    if (jj_scan_token(63)) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_41()
 {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_74()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_75()) return true;
    return false;
  }

  static private boolean jj_3_4()
 {
    if (jj_3R_27()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(72)) {
    jj_scanpos = xsp;
    if (jj_scan_token(73)) {
    jj_scanpos = xsp;
    if (jj_scan_token(74)) {
    jj_scanpos = xsp;
    if (jj_scan_token(75)) {
    jj_scanpos = xsp;
    if (jj_scan_token(24)) {
    jj_scanpos = xsp;
    if (jj_scan_token(23)) return true;
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_46()
 {
    if (jj_3R_28()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(76)) {
    jj_scanpos = xsp;
    if (jj_scan_token(77)) {
    jj_scanpos = xsp;
    if (jj_scan_token(78)) {
    jj_scanpos = xsp;
    if (jj_scan_token(79)) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_29()
 {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_46()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_28()) return true;
    return false;
  }

  static private boolean jj_3_3()
 {
    if (jj_3R_26()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(69)) {
    jj_scanpos = xsp;
    if (jj_scan_token(70)) {
    jj_scanpos = xsp;
    if (jj_scan_token(71)) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_45()
 {
    if (jj_3R_27()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(72)) {
    jj_scanpos = xsp;
    if (jj_scan_token(73)) {
    jj_scanpos = xsp;
    if (jj_scan_token(74)) {
    jj_scanpos = xsp;
    if (jj_scan_token(75)) {
    jj_scanpos = xsp;
    if (jj_scan_token(24)) {
    jj_scanpos = xsp;
    if (jj_scan_token(23)) return true;
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_28()
 {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_45()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_27()) return true;
    return false;
  }

  static private boolean jj_3_2()
 {
    if (jj_3R_25()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(67)) {
    jj_scanpos = xsp;
    if (jj_scan_token(68)) return true;
    }
    return false;
  }

  static private boolean jj_3R_44()
 {
    if (jj_3R_26()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(69)) {
    jj_scanpos = xsp;
    if (jj_scan_token(70)) {
    jj_scanpos = xsp;
    if (jj_scan_token(71)) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_27()
 {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_44()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_26()) return true;
    return false;
  }

  static private boolean jj_3_1()
 {
    if (jj_3R_24()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(64)) {
    jj_scanpos = xsp;
    if (jj_scan_token(65)) {
    jj_scanpos = xsp;
    if (jj_scan_token(66)) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_43()
 {
    if (jj_3R_25()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(67)) {
    jj_scanpos = xsp;
    if (jj_scan_token(68)) return true;
    }
    return false;
  }

  static private boolean jj_3R_26()
 {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_43()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_25()) return true;
    return false;
  }

  static private boolean jj_3R_42()
 {
    if (jj_3R_24()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(64)) {
    jj_scanpos = xsp;
    if (jj_scan_token(65)) {
    jj_scanpos = xsp;
    if (jj_scan_token(66)) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_25()
 {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_42()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_24()) return true;
    return false;
  }

  static private boolean jj_3R_99()
 {
    if (jj_3R_105()) return true;
    return false;
  }

  static private boolean jj_3R_40()
 {
    if (jj_scan_token(DELETE)) return true;
    if (jj_3R_73()) return true;
    return false;
  }

  static private boolean jj_3R_24()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_40()) {
    jj_scanpos = xsp;
    if (jj_3R_41()) return true;
    }
    return false;
  }

  static private boolean jj_3R_75()
 {
    if (jj_3R_73()) return true;
    return false;
  }

  static private boolean jj_3R_119()
 {
    if (jj_scan_token(57)) return true;
    if (jj_3R_118()) return true;
    return false;
  }

  static private boolean jj_3R_91()
 {
    if (jj_3R_94()) return true;
    return false;
  }

  static private boolean jj_3R_98()
 {
    if (jj_3R_104()) return true;
    return false;
  }

  static private boolean jj_3R_73()
 {
    if (jj_3R_91()) return true;
    return false;
  }

  static private boolean jj_3R_123()
 {
    if (jj_3R_125()) return true;
    return false;
  }

  static private boolean jj_3R_118()
 {
    if (jj_scan_token(IDENTIFIER_NAME)) return true;
    if (jj_scan_token(61)) return true;
    if (jj_3R_68()) return true;
    return false;
  }

  static private boolean jj_3R_113()
 {
    if (jj_3R_111()) return true;
    return false;
  }

  static private boolean jj_3R_97()
 {
    if (jj_3R_103()) return true;
    return false;
  }

  static private boolean jj_3R_109()
 {
    if (jj_3R_114()) return true;
    return false;
  }

  static private boolean jj_3R_114()
 {
    if (jj_3R_118()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_119()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_117()
 {
    if (jj_3R_111()) return true;
    if (jj_3R_116()) return true;
    return false;
  }

  static private boolean jj_3R_72()
 {
    if (jj_3R_34()) return true;
    return false;
  }

  static private boolean jj_3R_104()
 {
    if (jj_scan_token(59)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_109()) jj_scanpos = xsp;
    if (jj_scan_token(60)) return true;
    return false;
  }

  static private boolean jj_3R_125()
 {
    if (jj_scan_token(58)) return true;
    if (jj_3R_68()) return true;
    return false;
  }

  static private boolean jj_3R_96()
 {
    if (jj_3R_102()) return true;
    return false;
  }

  static private boolean jj_3R_108()
 {
    if (jj_3R_112()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_113()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_116()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_122()) {
    jj_scanpos = xsp;
    if (jj_3R_123()) return true;
    }
    return false;
  }

  static private boolean jj_3R_122()
 {
    if (jj_3R_68()) return true;
    return false;
  }

  static private boolean jj_3R_112()
 {
    if (jj_3R_116()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_117()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_19()
 {
    if (jj_3R_38()) return true;
    return false;
  }

  static private boolean jj_3R_107()
 {
    if (jj_3R_111()) return true;
    return false;
  }

  static private boolean jj_3R_111()
 {
    Token xsp;
    if (jj_scan_token(57)) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_scan_token(57)) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_103()
 {
    if (jj_scan_token(55)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_107()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3R_108()) jj_scanpos = xsp;
    if (jj_scan_token(56)) return true;
    return false;
  }

  static private boolean jj_3_20()
 {
    if (jj_3R_38()) return true;
    return false;
  }

  static private boolean jj_3R_102()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(35)) {
    jj_scanpos = xsp;
    if (jj_scan_token(36)) {
    jj_scanpos = xsp;
    if (jj_scan_token(38)) {
    jj_scanpos = xsp;
    if (jj_scan_token(37)) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_94()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(28)) {
    jj_scanpos = xsp;
    if (jj_scan_token(54)) {
    jj_scanpos = xsp;
    if (jj_3R_96()) {
    jj_scanpos = xsp;
    if (jj_3R_97()) {
    jj_scanpos = xsp;
    if (jj_3R_98()) {
    jj_scanpos = xsp;
    if (jj_3R_99()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_120()
 {
    if (jj_3R_124()) return true;
    return false;
  }

  static private boolean jj_3R_126()
 {
    if (jj_scan_token(57)) return true;
    if (jj_scan_token(IDENTIFIER_NAME)) return true;
    return false;
  }

  static private boolean jj_3_21()
 {
    if (jj_3R_39()) return true;
    return false;
  }

  static private boolean jj_3R_70()
 {
    Token xsp;
    if (jj_3_21()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_21()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_121()
 {
    if (jj_3R_124()) return true;
    return false;
  }

  static private boolean jj_3R_71()
 {
    if (jj_3R_35()) return true;
    return false;
  }

  static private boolean jj_3R_39()
 {
    Token xsp;
    xsp = jj_scanpos;
    jj_lookingAhead = true;
    jj_semLA = getToken(1).image != "function";
    jj_lookingAhead = false;
    if (!jj_semLA || jj_3R_71()) {
    jj_scanpos = xsp;
    if (jj_3R_72()) return true;
    }
    return false;
  }

  static private boolean jj_3R_38()
 {
    if (jj_3R_70()) return true;
    return false;
  }

  static private boolean jj_3R_124()
 {
    if (jj_scan_token(IDENTIFIER_NAME)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_126()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_133()
 {
    if (jj_3R_138()) return true;
    return false;
  }

  static private boolean jj_3R_115()
 {
    if (jj_scan_token(FUNCTION)) return true;
    if (jj_scan_token(88)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_121()) jj_scanpos = xsp;
    if (jj_scan_token(89)) return true;
    if (jj_scan_token(59)) return true;
    xsp = jj_scanpos;
    if (jj_3_20()) jj_scanpos = xsp;
    if (jj_scan_token(60)) return true;
    return false;
  }

  static private boolean jj_3R_34()
 {
    if (jj_scan_token(FUNCTION)) return true;
    if (jj_scan_token(IDENTIFIER_NAME)) return true;
    if (jj_scan_token(88)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_120()) jj_scanpos = xsp;
    if (jj_scan_token(89)) return true;
    if (jj_scan_token(59)) return true;
    xsp = jj_scanpos;
    if (jj_3_19()) jj_scanpos = xsp;
    if (jj_scan_token(60)) return true;
    return false;
  }

  static private boolean jj_3R_138()
 {
    if (jj_scan_token(FINALLY)) return true;
    if (jj_3R_77()) return true;
    return false;
  }

  static private boolean jj_3R_132()
 {
    if (jj_3R_137()) return true;
    return false;
  }

  static private boolean jj_3R_146()
 {
    if (jj_scan_token(CATCH)) return true;
    if (jj_scan_token(88)) return true;
    if (jj_scan_token(IDENTIFIER_NAME)) return true;
    if (jj_scan_token(89)) return true;
    if (jj_3R_77()) return true;
    return false;
  }

  static private boolean jj_3R_143()
 {
    if (jj_3R_146()) return true;
    return false;
  }

  static private boolean jj_3R_137()
 {
    Token xsp;
    if (jj_3R_143()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_143()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_67()
 {
    if (jj_3R_37()) return true;
    return false;
  }

  static private boolean jj_3_18()
 {
    if (jj_3R_37()) return true;
    return false;
  }

  static private boolean jj_3R_88()
 {
    if (jj_scan_token(TRY)) return true;
    if (jj_3R_77()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_132()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3R_133()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_87()
 {
    if (jj_scan_token(THROW)) return true;
    if (jj_3R_37()) return true;
    return false;
  }

  static private boolean jj_3_17()
 {
    if (jj_scan_token(IDENTIFIER_NAME)) return true;
    return false;
  }

  static private boolean jj_3R_129()
 {
    if (jj_3R_34()) return true;
    return false;
  }

  static private boolean jj_3R_131()
 {
    if (jj_3R_136()) return true;
    return false;
  }

  static private boolean jj_3_16()
 {
    if (jj_scan_token(IDENTIFIER_NAME)) return true;
    return false;
  }

  static private boolean jj_3R_86()
 {
    if (jj_scan_token(RETURN)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_18()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_66()
 {
    if (jj_3R_37()) return true;
    return false;
  }

  static private boolean jj_3R_85()
 {
    if (jj_scan_token(BREAK)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_17()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_84()
 {
    if (jj_scan_token(CONTINUE)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_16()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_93()
 {
    if (jj_scan_token(VAR)) return true;
    if (jj_3R_95()) return true;
    return false;
  }

  static private boolean jj_3R_142()
 {
    if (jj_scan_token(VAR)) return true;
    if (jj_3R_100()) return true;
    return false;
  }

  static private boolean jj_3R_136()
 {
    if (jj_3R_142()) return true;
    if (jj_scan_token(IN)) return true;
    if (jj_3R_37()) return true;
    return false;
  }

  static private boolean jj_3_15()
 {
    if (jj_3R_36()) return true;
    return false;
  }

  static private boolean jj_3R_90()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_92()) {
    jj_scanpos = xsp;
    if (jj_3R_93()) return true;
    }
    return false;
  }

  static private boolean jj_3R_92()
 {
    if (jj_3R_37()) return true;
    return false;
  }

  static private boolean jj_3R_141()
 {
    if (jj_3R_139()) return true;
    return false;
  }

  static private boolean jj_3R_65()
 {
    if (jj_3R_90()) return true;
    return false;
  }

  static private boolean jj_3R_148()
 {
    if (jj_3R_35()) return true;
    return false;
  }

  static private boolean jj_3R_36()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_65()) jj_scanpos = xsp;
    if (jj_scan_token(86)) return true;
    xsp = jj_scanpos;
    if (jj_3R_66()) jj_scanpos = xsp;
    if (jj_scan_token(86)) return true;
    xsp = jj_scanpos;
    if (jj_3R_67()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_83()
 {
    if (jj_scan_token(FOR)) return true;
    if (jj_scan_token(88)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_15()) {
    jj_scanpos = xsp;
    if (jj_3R_131()) return true;
    }
    if (jj_scan_token(89)) return true;
    if (jj_3R_35()) return true;
    return false;
  }

  static private boolean jj_3_14()
 {
    if (jj_scan_token(ELSE)) return true;
    if (jj_3R_35()) return true;
    return false;
  }

  static private boolean jj_3R_145()
 {
    if (jj_3R_35()) return true;
    return false;
  }

  static private boolean jj_3R_82()
 {
    if (jj_scan_token(WHILE)) return true;
    if (jj_scan_token(88)) return true;
    if (jj_3R_37()) return true;
    if (jj_scan_token(89)) return true;
    if (jj_3R_35()) return true;
    return false;
  }

  static private boolean jj_3R_135()
 {
    if (jj_3R_140()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_141()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_81()
 {
    if (jj_scan_token(DO)) return true;
    if (jj_3R_35()) return true;
    if (jj_scan_token(WHILE)) return true;
    if (jj_scan_token(88)) return true;
    if (jj_3R_37()) return true;
    if (jj_scan_token(89)) return true;
    return false;
  }

  static private boolean jj_3R_140()
 {
    if (jj_scan_token(DFLT)) return true;
    if (jj_scan_token(61)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_145()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_147()
 {
    if (jj_scan_token(CASE)) return true;
    if (jj_3R_37()) return true;
    if (jj_scan_token(61)) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_148()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_128()
 {
    if (jj_3R_35()) return true;
    return false;
  }

  static private boolean jj_3R_144()
 {
    if (jj_3R_147()) return true;
    return false;
  }

  static private boolean jj_3R_139()
 {
    Token xsp;
    if (jj_3R_144()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_144()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_134()
 {
    if (jj_3R_139()) return true;
    return false;
  }

  static private boolean jj_3R_130()
 {
    if (jj_scan_token(59)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_134()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_3R_135()) jj_scanpos = xsp;
    if (jj_scan_token(60)) return true;
    return false;
  }

  static private boolean jj_3R_80()
 {
    if (jj_scan_token(SWITCH)) return true;
    if (jj_scan_token(88)) return true;
    if (jj_3R_37()) return true;
    if (jj_scan_token(89)) return true;
    if (jj_3R_130()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public JavascriptTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  /** Whether we are looking ahead. */
  static private boolean jj_lookingAhead = false;
  static private boolean jj_semLA;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[44];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	   jj_la1_init_2();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x10200000,0x0,0x0,0x0,0x10200000,0x0,0x10200000,0x0,0x0,0x80000000,0x80000000,0x90210000,0x0,0x0,0x0,0x1800000,0x0,0x0,0x0,0x200000,0x0,0x7c724800,0x0,0x0,0x7c724800,0x200000,0x1000,0x1000,0x8000,0x1000,0x7c724800,0x7c724800,0x0,0x10200000,0x10200000,0x10200000,0x10200000,0x2000,0x80000,0x2000,0x0,0x0,0x0,0x200000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x8c00078,0x78,0x2000000,0x2000000,0xcc00078,0x2000000,0xcc00078,0x400000,0x2000000,0xc0000002,0xc0000002,0xc8c0007a,0x0,0x0,0x0,0x0,0x0,0x0,0x2000000,0x0,0x1,0x8c0007c,0x2000000,0x0,0x8c0007d,0x0,0x0,0x0,0x0,0x0,0x8c0007d,0x8c0007d,0x1,0x8c00079,0x8c00078,0x8c00078,0x8c00079,0x0,0x0,0x0,0x400000,0x400000,0x2000000,0x0,};
	}
	private static void jj_la1_init_2() {
	   jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x7,0x18,0xe0,0xf00,0xf000,0x200000,0x0,0x0,0x400000,0x0,0x0,0x800000,0x400000,0x0,0x0,0x0,0x0,0x0,0x400000,0x400000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
	}
  static final private JJCalls[] jj_2_rtns = new JJCalls[21];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  {
      enable_tracing();
  }
  /** Constructor with InputStream. */
  public Javascript(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Javascript(java.io.InputStream stream, String encoding) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser.  ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new JavascriptTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 44; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 44; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Javascript(java.io.Reader stream) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new JavascriptTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 44; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new JavascriptTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 44; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Javascript(JavascriptTokenManager tm) {
	 if (jj_initialized_once) {
	   System.out.println("ERROR: Second call to constructor of static parser. ");
	   System.out.println("	   You must either use ReInit() or set the JavaCC option STATIC to false");
	   System.out.println("	   during parser generation.");
	   throw new Error();
	 }
	 jj_initialized_once = true;
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 44; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(JavascriptTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 44; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   trace_token(token, "");
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	   trace_token(token, " (in getNextToken)");
	 return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
	 Token t = jj_lookingAhead ? jj_scanpos : token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  static private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[90];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 44; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		   if ((jj_la1_2[i] & (1<<j)) != 0) {
			 la1tokens[64+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 90; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  static private int trace_indent = 0;
  static private boolean trace_enabled;

/** Trace enabled. */
  static final public boolean trace_enabled() {
	 return trace_enabled;
  }

/** Enable tracing. */
  static final public void enable_tracing() {
	 trace_enabled = true;
  }

/** Disable tracing. */
  static final public void disable_tracing() {
	 trace_enabled = false;
  }

  static protected void trace_call(String s) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.println("Call:	" + s);
	 }
	 trace_indent = trace_indent + 2;
  }

  static protected void trace_return(String s) {
	 trace_indent = trace_indent - 2;
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.println("Return: " + s);
	 }
  }

  static protected void trace_token(Token t, String where) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.print("Consumed token: <" + tokenImage[t.kind]);
	   if (t.kind != 0 && !tokenImage[t.kind].equals("\"" + t.image + "\"")) {
		 System.out.print(": \"" + TokenMgrError.addEscapes(t.image) + "\"");
	   }
	   System.out.println(" at line " + t.beginLine + " column " + t.beginColumn + ">" + where);
	 }
  }

  static protected void trace_scan(Token t1, int t2) {
	 if (trace_enabled) {
	   for (int i = 0; i < trace_indent; i++) { System.out.print(" "); }
	   System.out.print("Visited token: <" + tokenImage[t1.kind]);
	   if (t1.kind != 0 && !tokenImage[t1.kind].equals("\"" + t1.image + "\"")) {
		 System.out.print(": \"" + TokenMgrError.addEscapes(t1.image) + "\"");
	   }
	   System.out.println(" at line " + t1.beginLine + " column " + t1.beginColumn + ">; Expected token: <" + tokenImage[t2] + ">");
	 }
  }

  static private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 21; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			   case 6: jj_3_7(); break;
			   case 7: jj_3_8(); break;
			   case 8: jj_3_9(); break;
			   case 9: jj_3_10(); break;
			   case 10: jj_3_11(); break;
			   case 11: jj_3_12(); break;
			   case 12: jj_3_13(); break;
			   case 13: jj_3_14(); break;
			   case 14: jj_3_15(); break;
			   case 15: jj_3_16(); break;
			   case 16: jj_3_17(); break;
			   case 17: jj_3_18(); break;
			   case 18: jj_3_19(); break;
			   case 19: jj_3_20(); break;
			   case 20: jj_3_21(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
